kimkyunghun3/WWDC

2015/Networking_with_NSURLSession.md
Networking with NSURLSession
https://developer.apple.com/videos/play/wwdc2015/711/
https://ssup2.github.io/theory_analysis/HTTP2/ 
https://velog.io/@wiostz98kr/HTTP1.1과-HTTP2.0의-차이-e2v4x4t1](https://velog.io/@wiostz98kr/HTTP1.1%EA%B3%BC-HTTP2.0%EC%9D%98-%EC%B0%A8%EC%9D%B4-e2v4x4t1)
=> [2015] 1주차 wwdc Networking with NSURLSession

2015/Building_Responsive_and_Efficient_Apps_with_GCD.md
@westeastyear @grumpy-sw 
Building Responsive and Efficient Apps with GCD
https://developer.apple.com/videos/play/wwdc2015/718/
https://h4njun.tistory.com/m/entry/동시성-프로그래밍3-DispatchQueue
https://developer.apple.com/documentation/dispatch/dispatch_block_flags_t/dispatch_block_assign_current
https://sujinnaljin.medium.com/ios-차근차근-시작하는-gcd-15-3fef697f9aab
https://jbear.tistory.com/entry/우선순위-전도-우선순위-상속-Priority-Inversion-Priority-Inheritance
=> [2015] 1주차 wwdc Building Responsive and Efficient Apps with GCD

2015/Mysteries of Auto Layout, Part 1, 2.md
https://developer.apple.com/videos/play/wwdc2015/218/
https://developer.apple.com/documentation/uikit/uiview/1622576-alignmentrect
https://developer.apple.com/videos/play/wwdc2015/219/
https://zeddios.tistory.com/1202
https://developer.apple.com/documentation/uikit/uilayoutguide
=> [2015] 1주차 wwdc Mysteries of Auto Layout, Part1, Part2

2015/Optimizing_Swift_Performance.md
Optimizing_Swift_Performance
https://developer.apple.com/videos/play/wwdc2015/409/
=> [2015] (2)주차  Optimizing_Swift_Performance

2015/what's new in lldb.md
https://developer.apple.com/videos/play/wwdc2015/402/
=> [2015] (2)주차 what's new in lldb

2019/SwiftUI Essentials.md
@cherrishRed
[WWDC SwiftUI Essentials](https://developer.apple.com/videos/play/wwdc2019/216/)
=> [2019] SwiftUI Essentials

2018/High_Performance_Auto_Layout.md
[WWDC  High Performance Auto Layout](https://developer.apple.com/videos/play/wwdc2018/220/)
=> [2018] High Performance Auto Layout

2018/Testing_Tips_and_Tricks.md
[Testing Tips & Tricks](https://developer.apple.com/videos/play/wwdc2018/417/)
=> [2018] Testing Tips & Tricks

2018/A_Tour_of_UICollectionView.md
[A Tour of UICollectionView](https://developer.apple.com/videos/play/wwdc2018/225/?time=2359)
=> [2018] A Tour of UICollectionView

2018/Advanced_Debugging_with_Xcode_and_LLDB.md
https://developer.apple.com/videos/play/wwdc2018/412/
=> [2018] Advanced Debugging with Xcode and LLDB

2019/Advances_in_Collection_View_Layout.md
[WWDC 19 - Advances in Collection View Layout](https://developer.apple.com/videos/play/wwdc2019/215/?time=2118)
=> [2019] Advances in Collection View Layout

2020/Advances_in_diffable_data_sources.md
[WWDC 보러가기](https://developer.apple.com/videos/play/wwdc2020/10045/?time=623)
=> [2020] Advances in diffable data sources

2019/Building Custim Views in SwiftUI.md
Building Custom Views in SwiftUI
https://developer.apple.com/videos/play/wwdc2019/237/
=> [2019] Building Custom Views in SwiftUI

2020/Advances_in_UICollectionView.md, 2020/Modern_Cell_Configuration.md
[Advances in UICollectionView](https://developer.apple.com/videos/play/wwdc2020/10097/?time=570)
[Modern Cell Configuration](https://developer.apple.com/videos/play/wwdc2020/10027/?time=1599)
=> add: Advances in UICollectionView & Modern Cell Configuration

2020/Get your test results faster.md
Get your test results faster
https://developer.apple.com/videos/play/wwdc2020/10221/
=> [2020] Get your test results faster

2021/DiscoverConcurrencyInSwiftUI.md
Discover concurrency in SwiftUI
https://developer.apple.com/videos/play/wwdc2021/10019/?time=445
=> [2021] Discover concurrency in SwiftUI

2021/DemystifySwiftUI.md
Demystify SwiftUI
https://developer.apple.com/videos/play/wwdc2021/10022/?time=1011
=> [2021] Demystify SwiftUI

2021/ Use async:await with URLSession.md
Use async/await with URLSession
https://developer.apple.com/videos/play/wwdc2021/10095/
=> [2021] Use async/await with URLSession

2020/Stacks, Grids, and Outlines in SwiftUI.md
Stacks, Grids, and Outlines in SwiftUI
https://developer.apple.com/videos/play/wwdc2020/10031/
=> [2020] Stacks, Grids, and Outlines in SwiftUI

2021/Detect_and_diagnose_memory_issues.md
[https://developer.apple.com/videos/play/wwdc2021/10180/?time=1675](https://developer.apple.com/videos/play/wwdc2021/10180/?time=1675)
=> [2021] Detect and diagnose memory issues

2021/Protect mutable state with Swift actors.md
Protect mutable state with Swift actors
https://developer.apple.com/videos/play/wwdc2021/10133/
=> [2021] Protect mutable state with Swift actors

2019/Introducing Combine.md
IntroducingCombine
https://developer.apple.com/videos/play/wwdc2019/722/
=> [2020] IntroducingCombine

2021/Swift Concurrency Behind the Scenes.md
Swift Concurrency Behind the Scenes
https://developer.apple.com/videos/play/wwdc2021/10254/
=> [2021] Swift Concurrency Behind the Scenes

2019/CombineInPractice.md
- Combine in Practice
- https://developer.apple.com/videos/play/wwdc2019/721/
=> [2019] Combine in Practice

2021/Explore structured concurrency in Swift.md
Explore structured concurrency in Swift
https://developer.apple.com/videos/play/wwdc2021/10134/
=> [2021] Explore structured concurrency in Swift

2020/Meet_WidgetKit.md, README.md
Meet WidgetKit
[Meet WidgetKit - WWDC20 - Videos - Apple Developer](https://developer.apple.com/videos/play/wwdc2020/10028/)
=> Meet WidgetKit

2015/UI_Testing_in_Xcode.md
[https://developer.apple.com/videos/play/wwdc2015/406](https://developer.apple.com/videos/play/wwdc2015/406)
=> [2015] UI Testing in Xcode

2020/Why Is My App Getting Killed?.md
Why Is My App Getting Killed?
https://developer.apple.com/videos/play/wwdc2020/10078/
=> [2020] Why Is My App Getting Killed?

2020/Eleminate_animation_hitches_with_XCTest.md
[https://developer.apple.com/videos/play/wwdc2020/10077/](https://developer.apple.com/videos/play/wwdc2020/10077/)
=> [2020] Eleminate animation hitches with XCTest

2021/Swift_concurrency_Update_a_sample_app.md
Swift concurrency: Update a sample app
https://developer.apple.com/videos/play/wwdc2021/10194/
=> [2021] Swift concurrency: Update a sample app

2021/Discover breakpoint improvements.md
- Discover breakpoint improvements
- https://developer.apple.com/videos/play/wwdc2021/10209/?time=292
=> [2021] Discover breakpoint improvements

2022/Use_SwiftUI_with_UIKit.md, README.md
- Use SwiftUI with UIKit
- https://developer.apple.com/videos/play/wwdc2022/10072/
=> [2022] Use SwiftUI with UIKit

2021/Customize_and_resize sheets_in_UIkit.md
=> [2021]Customize and resize sheets in UIkit

2021/Meet_Xcode_Cloud.md
Meet Xcode Cloud
https://developer.apple.com/videos/play/wwdc2021/10267/
=> [2021] Meet Xcode Cloud

2021/Diagnose Power and Performance regressions in your app.md
Diagnose Power and Performance regressions in your app
https://developer.apple.com/videos/play/wwdc2021/10087/
=> [2021] Diagnose Power and Performance regressions in your app

2021/Explore Xcode Cloud Workflows.md
Explore Xcode Cloud Workflows
https://developer.apple.com/videos/play/wwdc2021/10268/
=> [2021] Explore Xcode Cloud Workflows

2018/Using_Collections_Effectively.md
[https://developer.apple.com/videos/play/wwdc2018/229](https://developer.apple.com/videos/play/wwdc2018/229)
=> [2018] Using Collections Effectively

2020/Write_Tests_To_Fail.md
- Write tests to fail
- https://developer.apple.com/videos/play/wwdc2020/10091/
=> [2020] Write tests to fail

2020/Explore the new system architecture of Apple silicon Macs.md
Explore the new system architecture of Apple silicon Macs
https://developer.apple.com/videos/play/wwdc2020/10686/
=> [2020] Explore the new system architecture of Apple silicon Macs

2022/Meet_Swift_Regex.md
- Meet Swift Regex
[https://developer.apple.com/videos/play/wwdc2022/110357/](https://developer.apple.com/videos/play/wwdc2022/110357/)
=> [2022] Meet Swift Regex

2020/App Essentials in SwiftUI.md
App Essentials in SwiftUI
https://developer.apple.com/videos/play/wwdc2020/10037/
=> [2020] App Essentials in SwiftUI

2022/Swift_Regex:_Beyond_the_basics.md
Swift Regex: Beyond the basics
[https://developer.apple.com/videos/play/wwdc2022/110358](https://developer.apple.com/videos/play/wwdc2022/110358)
=> [2022] Swift Regex: Beyond the basics

2020/Whta's new in SwiftUI.md
- What's new in SwiftUI
- https://developer.apple.com/videos/play/wwdc2020/10041/
=> [2020] What's new in SwiftUI

2018/Getting to Know Swift Package Manager.md
Getting to Know Swift Package Manager
https://developer.apple.com/videos/play/wwdc2018/411/
=> [2018] Getting to Know Swift Package Manager

2022/WWDC 2022 what’s new in UIKit.md
what’s new in UIKit
[what’s new in UIKit](https://developer.apple.com/videos/play/wwdc2022/10068/)
=> add: what’s new in UIKit

2018/Embracing_Algorithms.md
Embracing Algorithms
[https://developer.apple.com/videos/play/wwdc2018/223](https://developer.apple.com/videos/play/wwdc2018/223)
=> [2018] Embracing Algorithms

2021/Meet_the_Swift_Algorithms_and_Collections_packages.md
[https://developer.apple.com/videos/play/wwdc2021/10256](https://developer.apple.com/videos/play/wwdc2021/10256)
=> [2021] Meet the Swift Algorithms and Collections packages

2018/Building Faster in Xcode.md
Building Faster in Xcode
https://developer.apple.com/videos/play/wwdc2018/408/
=> [2018] Building Faster in Xcode

2020/Boost Performance and security with modern networking.md
- Boost performance and security with modern networking
- https://developer.apple.com/videos/play/wwdc2020/10111/
=> [2020] Boost performance and security with modern networking

2019/Implementing_Dark_Mode_on_iOS.md
[https://developer.apple.com/videos/play/wwdc2019/214](https://developer.apple.com/videos/play/wwdc2019/214)
=> [2019] Implementing Dark Mode on iOS

2019/Optimizing App Launch.md
Optimizing App Launch
https://developer.apple.com/videos/play/wwdc2019/423/
=> [2019] Optimizing App Launch

2022/Hello_Swift_Charts.md, README.md
Hello Swift Charts
https://developer.apple.com/videos/play/wwdc2022/10136/
=> [2022] Hello Swift Charts

2021/Understand and eliminate hangs from your app.md
Understand and eliminate hangs from your app
https://developer.apple.com/videos/play/wwdc2021/10258/
=> [2021] Understand and eliminate hangs from your app

2022/What's new in privacy.md
What's new in privacy
https://developer.apple.com/videos/play/wwdc2022/10096/
=> [2022] What's new in privacy

2019/Introducing_Core_Haptics.md
[https://developer.apple.com/videos/play/wwdc2019/520](https://developer.apple.com/videos/play/wwdc2019/520)
=> [2019] Introducing Core Haptics

2023/Implement Apple Pay and order management.md
Implement Apple Pay and order management
https://developer.apple.com/videos/play/tech-talks/110336/
=> [2023] Implement Apple Pay and order management

2022/Get_to_know_Developer_Mode.md, README.md
Get to know Developer Mode
https://developer.apple.com/videos/play/wwdc2022/110344/
=> [2022] Get to know Developer Mode

2022/What's_new_in_Photos_picker.md
[https://developer.apple.com/videos/play/wwdc2022/10023](https://developer.apple.com/videos/play/wwdc2022/10023)
=> [2022] What's new in Photos picker

2022/Build global apps_Localization by example.md
Build global apps: Localization by example
https://developer.apple.com/videos/play/wwdc2022/10110/
=> [2022] Build global apps: Localization by example

2018/Image_and_Graphics_Best_Practices.md
[https://developer.apple.com/videos/play/wwdc2018/219](https://developer.apple.com/videos/play/wwdc2018/219)
=> [2018] Image and Graphics Best Practices

2020/The Push Notifications primer.md
- The Push Notifications primer
- https://developer.apple.com/videos/play/wwdc2020/10095/
=> [2020] The Push Notifications primer

2022/Enhance your Sign in with Apple experience.md
Enhance your Sign in with Apple experience
https://developer.apple.com/videos/play/wwdc2022/10122/
=> [2022] Enhance your Sign in with Apple experience

2019/CryptographyAndYourApp.md
- Cryptography And Your Apps
- https://developer.apple.com/videos/play/wwdc2019/709/
=> [WWDC] Cryptography And Your Apps

2021/Customize your advanced Xcode Cloud workflows.md
Customize your advanced Xcode Cloud workflows
https://developer.apple.com/videos/play/wwdc2021/10269/
=> [2021] Customize your advanced Xcode Cloud workflows

2018/UIKit:_Apps_for_Every_Size_and_Shape.md
[https://developer.apple.com/videos/play/wwdc2018/235/](https://developer.apple.com/videos/play/wwdc2018/235/)
=> [2018] UIKit: Apps for Every Size and Shape

2023/What's new in SwiftUI.md
[https://developer.apple.com/videos/play/wwdc2023/10148/](https://developer.apple.com/videos/play/wwdc2023/10148/)
=> [2023] What's new in SwiftUI
